//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirNautisService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airplane
    {
        public Airplane()
        {
            this.Travel = new HashSet<Travel>();
        }
    
        public int Id { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public int Capacity { get; set; }
        public Nullable<int> Hangar { get; set; }
        public bool Active { get; set; }
    
        public virtual Hangar Hangar1 { get; set; }
        public virtual ICollection<Travel> Travel { get; set; }
    }
}
