//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirNautisService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel
    {
        public System.DateTime Date { get; set; }
        public int Airplane { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
    
        public virtual Airplane Airplane1 { get; set; }
    }
}
